#!/bin/env -S ansible-playbook -i inventory
---
- name: manage ios host
  hosts: all
  gather_facts: false

  pre_tasks:

    - name: Fail if not ios
      ansible.builtin.fail:
      no_log: true
      when: ansible_network_os != "cisco.ios.ios"

    - name: Gather all legacy facts
      connection: ansible.netcommon.network_cli
      cisco.ios.ios_facts:
        gather_subset: all

  tasks:

    - ansible.builtin.include_tasks: ios_system.yaml
