#!/bin/env -S ansible-playbook -i inventory
---
- name: manage ios host
  hosts: all
  gather_facts: false

  pre_tasks:

    - name: Fail if not ios
      ansible.builtin.fail:
      no_log: true
      when: ansible_network_os != "cisco.ios.ios"

    - name: Gather all legacy facts
      connection: ansible.netcommon.network_cli
      cisco.ios.ios_facts:
        gather_subset: all

  tasks:

#    - ansible.builtin.debug:
#        msg: "{{ ansible_facts }}"
#    - meta: end_play

    - ansible.builtin.include_tasks: "{{ include }}"
      loop_control:
        loop_var: include
      loop:
        - ios_system.yaml
        - ios_switch.yaml

